### ISSUE TITLE
Pre trained model

### ISSUE THREAD

**Issue by sulakshgupta988** [guyii54/JRGR#2]
Kudos on the great work!

Would it be possible for you to provide the pre-trained model for testing purposes? 

Thanks

**Comment by imissrc** [comment]
hello， Can you upload pre-trained models like this: './checkpoints/JRGR/latest_net_G1.pth'?
Thank you very much!

**Comment by guyii54** [comment]
Thanks for your interests for our work. The pretrained model and the final model have been uploaded now (links in the updated readme.md). The models for the real dataset will be released soon along with a number of real captured photos.
